# Generated by Django 5.1.3 on 2025-03-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="description",
        ),
    ]
