# Generated by Django 5.1.3 on 2025-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_remove_home_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Home",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
