# Generated by Django 5.1.3 on 2025-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_aboutme_additional_info_programmingskill"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="additional_info",
            field=models.TextField(
                blank=True, help_text="Qo‘shimcha ma'lumotlar", null=True
            ),
        ),
    ]
